package pt.isel.pdm.gomokuroyale.http.utils

object Rels {
    const val HOME = "home"
    const val SYSTEM_INFO = "system-info"
    const val REGISTER = "create-a-user"
    const val LOGIN = "login"
    const val LOGOUT = "logout"
    const val USER = "get-user-by-id"
    const val AUTH_HOME = "auth-home"
    const val RANKING_INFO = "ranking-info"
    const val GET_STATS_BY_USERNAME_FOR_RANKING = "get-stats-by-username-for-ranking"
    const val USER_STATS = "get-user-stats"
    const val USER_STATS_BY_USERNAME = "get-user-stats-by-username"
    const val UPDATE_USER = "update-user"
    const val GAME = "get-game-by-id"
    const val PLAY = "play"
    const val MATCHMAKING = "matchmaking"
    const val MATCHMAKING_STATUS = "get-matchmaking-status"
    const val LEAVE = "leave"
    const val GET_ALL_GAMES = "get-all-games"
    const val GET_ALL_GAMES_BY_USER = "get-all-games-by-user"
    const val EXIT_MATCHMAKING_QUEUE = "exit-matchmaking-queue"
    const val GET_ALL_VARIANTS = "get-all-variants"
}
